ControlObligaciones/ControlObligacionesWeb/src/main/java/mx/gob/sat/siat/cob/seguimiento/web/controller/bean/backing/AprobarMultaGruposManagedBean.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.gob.sat.siat.cob.seguimiento.web.controller.bean.backing;


import javax.annotation.PostConstruct;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpSession;
import mx.gob.sat.siat.cob.seguimiento.dto.stdcob.AdministrativoNivelCargo;
import mx.gob.sat.siat.cob.seguimiento.dto.stdcob.MultaAprobarGrupo;
import mx.gob.sat.siat.cob.seguimiento.dto.stdcob.enums.EventoCargaEnum;
import mx.gob.sat.siat.cob.seguimiento.exception.SGTServiceException;
import mx.gob.sat.siat.cob.seguimiento.service.aprobacion.AprobarMultasService;
import mx.gob.sat.siat.cob.seguimiento.service.aprobacion.impl.AprobarMultasCountThread;
import mx.gob.sat.siat.cob.seguimiento.service.otros.AdministracionFuncionariosService;
import mx.gob.sat.siat.cob.seguimiento.util.IntegerMutable;
import mx.gob.sat.siat.cob.seguimiento.util.constante.ConstantsCatalogos;
import mx.gob.sat.siat.cob.seguimiento.utils.AbstractBaseMB;
import mx.gob.sat.siat.cob.seguimiento.web.controller.bean.backing.helper.AprobarMultaGruposManagedBeanHelper;
import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

/**
 *
 * @author root
 */
@Controller("aprobarMultaGruposMB")
@Scope(value = "view")
public class AprobarMultaGruposManagedBean extends AbstractBaseMB  {
    @Autowired
    private AprobarMultasService aprobarMultasService;
    @Autowired
    private AdministracionFuncionariosService administracionFuncionariosService;
    @Autowired
    private ApplicationContext applicationContext;
    private AprobarMultaGruposManagedBeanHelper aprobarMultaGruposManagedBeanHelper;
    private boolean botonDescargaVisible = false;
    private Integer progress = 0;
    private AprobarMultasCountThread thread;
    private AdministrativoNivelCargo administrativo;

    public AprobarMultaGruposManagedBean() {
        aprobarMultaGruposManagedBeanHelper = new AprobarMultaGruposManagedBeanHelper();
        aprobarMultaGruposManagedBeanHelper.setNombreArchivoDescarga((String) ((HttpSession) FacesContext.
                getCurrentInstance().
                getExternalContext().
                getSession(true)).
                getAttribute("archivoResultadosEmisionMulta"));
        ((HttpSession) FacesContext.
                getCurrentInstance().
                getExternalContext().
                getSession(true)).removeAttribute("archivoResultadosEmisionMulta");
        if(aprobarMultaGruposManagedBeanHelper.getNombreArchivoDescarga()!=null){
            botonDescargaVisible = true;
        }
    }
    @PostConstruct
    public void init() {
        try {
            obtenerAccesoUsrEmpleados();
            autorizar(ConstantsCatalogos.IDENTIFICADOR_EMISION_MULTAS);
            administrativo = administracionFuncionariosService.buscarCargoAdministrativo(this.getAccesoUsr().getNumeroEmp(), EventoCargaEnum.CARGA_OMISOS);
            aprobarMultaGruposManagedBeanHelper.setListaMultasGrupo(aprobarMultasService.listarMultasAgrupadas(administrativo));
            aprobarMultaGruposManagedBeanHelper.setProgress(new IntegerMutable());
            aprobarMultaGruposManagedBeanHelper.getProgress().setValor(0);
        } catch (SGTServiceException ex) {
            this.getLogger().error(ex);
            addErrorMessage("Error", ex.getMessage());
        }
    }

    public AprobarMultaGruposManagedBeanHelper getAprobarMultaGruposManagedBeanHelper() {
        return aprobarMultaGruposManagedBeanHelper;
    }

    public void setAprobarMultaGruposManagedBeanHelper(AprobarMultaGruposManagedBeanHelper aprobarMultaGruposManagedBeanHelper) {
        this.aprobarMultaGruposManagedBeanHelper = aprobarMultaGruposManagedBeanHelper;
    }
    
    //Se agrega processo thread
    public void setMultaAprobarGrupo(MultaAprobarGrupo multaAprobarGrupo) {
        try {            
            thread = applicationContext.getBean(AprobarMultasCountThread.class);
            thread.establecerValoresEjecucion(multaAprobarGrupo,
                                            administrativo,
                                            aprobarMultaGruposManagedBeanHelper.getProgress());
            thread.start();
            
            getSession().setAttribute("multaAprobarGrupo", multaAprobarGrupo);
            
        }catch(Exception e){
            getLogger().error(e.getMessage());
        }
    }

    public boolean isBotonDescargaVisible() {
        return botonDescargaVisible;
    }
    
    public StreamedContent getDescargaEmision() {
        StreamedContent sc = null;
        try {
            sc = new DefaultStreamedContent(aprobarMultasService.generarArchivoEmision(aprobarMultaGruposManagedBeanHelper.getNombreArchivoDescarga()),
                                                 "application/pdf", aprobarMultaGruposManagedBeanHelper.getNombreArchivoDescarga());
        } catch (SGTServiceException e) {
            this.getLogger().error(e);
            addErrorMessage("Error", e.getMessage());
            aprobarMultaGruposManagedBeanHelper.setMultaAprobarDescarga(null);
            botonDescargaVisible=false;
        }
        return sc;
    }
    public void mensajeEmision(){
        if(aprobarMultaGruposManagedBeanHelper.getMultaAprobarDescarga()!=null){
            if(aprobarMultaGruposManagedBeanHelper.getMultaAprobarDescarga().getCantidadPosiblesEmitir().
                    equals(aprobarMultaGruposManagedBeanHelper.getMultaAprobarDescarga().getCantidadMultasEmitidas())){
                addMessage(null, "Los multas fueron emitidas exitosamente. Verifique el archivo de descarga");
            }else{
                addErrorMessage("Error", "No todas las multas pudieron ser emitidas. Verifique el archivo de descarga");
            }
            botonDescargaVisible = true;
        }
        
    }

    public Integer getProgress() {
        return progress;
    }

    public void setProgress(Integer progress) {
        this.progress = progress;
    }
    
    public void increment() {
        progress++;
        this.getLogger().debug("\nel número de llamadas del poll va en " + progress);
    }
    
    public void irMultasIndividuales() {
        MultaAprobarGrupo multaAprobarGrupo = (MultaAprobarGrupo) getSession().getAttribute("multaAprobarGrupo");

        if (thread.getNumeroElementos() != null) {
            multaAprobarGrupo.setConteoElementos(thread.getNumeroElementos());
        }

        if (thread.getException() != null) {
            getLogger().error(thread.getException().getMessage());
        }

        getSession().setAttribute("multaAprobarGrupo", multaAprobarGrupo);
        
        redirigir("/pages/cob/aprobarVigilancias/aprobarMulta.jsf");

    }
}

ControlObligaciones/ControlObligacionesWeb/src/main/java/mx/gob/sat/siat/cob/seguimiento/web/controller/bean/backing/CargaRenuentesBisManagedBean.java
package mx.gob.sat.siat.cob.seguimiento.web.controller.bean.backing;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.Charset;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.annotation.PostConstruct;
import mx.gob.sat.siat.cob.seguimiento.dto.stdcob.DatosCargaRenuentes;
import mx.gob.sat.siat.cob.seguimiento.dto.stdcob.Documento;
import mx.gob.sat.siat.cob.seguimiento.dto.stdcob.EstadoDocumento;
import mx.gob.sat.siat.cob.seguimiento.exception.SGTServiceException;
import mx.gob.sat.siat.cob.seguimiento.service.renuente.BuscaRenuentesService;
import mx.gob.sat.siat.cob.seguimiento.service.renuente.DoctoRenuenteService;
import mx.gob.sat.siat.cob.seguimiento.util.constante.ConstantsCatalogos;
import mx.gob.sat.siat.cob.seguimiento.utils.AbstractBaseMB;
import mx.gob.sat.siat.cob.seguimiento.web.util.ConstantesWeb;
import mx.gob.sat.siat.controlador.AccesoProceso;
import mx.gob.sat.siat.exception.AccesoDenegadoException;
import mx.gob.sat.siat.exception.AccesoDenegadoFielException;
import mx.gob.sat.siat.exception.SessionRolNullException;
import mx.gob.sat.siat.modelo.dto.SegbMovimientoDTO;
import mx.gob.sat.siat.util.MovimientoUtil;
import org.apache.commons.io.output.FileWriterWithEncoding;
import org.primefaces.event.FileUploadEvent;
import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;
import org.primefaces.model.UploadedFile;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;


/**
 *
 * @author Marco Murakami
 */
@Controller("cargaRenuentesBis")
@Scope(value = "view")
public class CargaRenuentesBisManagedBean extends AbstractBaseMB {
    @SuppressWarnings("compatibility:-1737564122481946159")
    private static final long serialVersionUID = 302L;
    @Autowired
    private DoctoRenuenteService doctoRenuenteService;
    @Autowired
    private transient BuscaRenuentesService buscaRenuentesService;
    @Value("#{properties['filename.renuentes.bitacora']}")
    private String bitacoraFileName;
    private String fileBitacoraFullName;
    private List<DatosCargaRenuentes> listaDatosCarga;
    private boolean showButtonBitacora;
    private UploadedFile file;

    @PostConstruct
    public void init() {
        obtenerAccesoUsrEmpleados();
        try {
            AccesoProceso.validaAccesoProceso(getSession(), ConstantsCatalogos.IDENTIFICADOR_CARGARENUENTESBIS, ConstantsCatalogos.PARAMETRO_FIEL);
        } catch (SessionRolNullException ex) {
            getLogger().error(ex);
            redirecionarPaginaError(ex);
        } catch (AccesoDenegadoException ex) {
            getLogger().error(ex);
            redirecionarPaginaError(ex);
        } catch (AccesoDenegadoFielException ex) {
            getLogger().error(ex);
            redirecionarPaginaError(ex);
        }
    }

    /**
     * Metodo para descargar la bitacora de errores
     *
     * @return
     */
    public StreamedContent getBitacoraFile() {
        StreamedContent sc = null;
        try {
            sc = this.getFile(this.fileBitacoraFullName);
        } catch (IOException ioe) {
            addErrorMessage(ConstantesWeb.ERROR, ioe.getMessage());
        }
        return sc;
    }

    /**
     * Metodo para la descarga del archivo de renuentes
     *
     * @param nameFile
     * @param ext
     * @return
     * @throws IOException
     */
    private StreamedContent getFile(String fileFullName) throws IOException {
       
        File arc = new File(fileFullName);
        InputStream is = new FileInputStream(arc);
        StreamedContent sc = new DefaultStreamedContent(is, "text/plain", arc.getName());
       
        return sc;
    }

    /**
     * Metodo para guardar el archivo en el servidor
     *
     * @param content
     * @param nameFile
     * @param ext
     * @throws IOException
     */
    private void saveFile(String content, String nameFile) throws IOException {
        String nombre = getFileName(nameFile);

        if (nameFile.equals(bitacoraFileName)) {
            fileBitacoraFullName = nombre;
        }
        File archivo = new File(nombre);
        if (!archivo.exists()) {
            boolean resp = archivo.createNewFile();
            if (resp) {
                BufferedWriter bw = new BufferedWriter(new FileWriterWithEncoding(archivo.getAbsoluteFile(), Charset.defaultCharset()));
                bw.write(content);
                bw.close();
            }
        }
      
    }

    /**
     * @param event
     */
    public void handleFileUpload(FileUploadEvent event) {
        addMessage("Succesful", event.getFile().getFileName() + " is uploaded.");

        try {
            leerArchivo(event.getFile().getFileName(), event.getFile().getInputstream());
        } catch (IOException ioE) {
            getLogger().error(ioE.getMessage());
        }
    }
    
    public void procesarArchivo(){
        if (file != null){
            try {
                leerArchivo(file.getFileName(), file.getInputstream());
            } catch (IOException ex) {
                getLogger().error(ex.getMessage());
            }
        }
    }

    /**
     * @param nombreArchivo
     * @param is
     */
    public void leerArchivo(String nombreArchivo, InputStream is) {

        BufferedReader br = null;
        String line;
        boolean resp;
        int totalReg = 0;
        int badReg = 0;
        int goodReg = 0;
        List<String> listaErrores = new ArrayList<String>();

        try {
            br = new BufferedReader(new InputStreamReader(is, Charset.defaultCharset()));

            while ((line = br.readLine()) != null) {

                //BUSQUEDA DEL DOCUMENTO POR NUMERO DE CONTROL
                Documento documento = buscaXNumControl(line);
                totalReg++;
                if (documento != null) {
                    //BUSQUEDA DEL ESTADO DEL DOCUMENTO
                    EstadoDocumento ed = this.buscaEstadoDoctoXNumControl(line);
                    if (ed == null) {
                        //ACTUALIZACION DEL DOCUMENTO
                        resp = updateRenuente(line);
                        if (resp) {
                            goodReg++;
                        } else {
                            badReg++;
                            listaErrores.add(line);
                        }//Proceso por renglon
                    } else {
                        //NO SE ACTUALIZA EL DOCUMENTO DEBIDO A QUE TIENE UN ESTADO DE CANCELACION
                        badReg++;
                        listaErrores.add(line + " | " + ed.getNombreEstado());
                    }
                } else {
                    //NO SE ENCUENTRA EL DOCUMENTO EN LA BASE DE DATOS
                    badReg++;
                    listaErrores.add(line + " | Inconsistencia de datos.");
                }
            }
            // ACORTA NOMBRE DEL ARCHIVO
            String shortFileName = null;
            if (nombreArchivo.contains("\\")) {
                String[] rutaAbsoluta = nombreArchivo.split("\\\\");
                shortFileName = rutaAbsoluta[rutaAbsoluta.length - 1];
            } else {
                shortFileName = nombreArchivo;
            }

            DatosCargaRenuentes datosCargaRenuentes = new DatosCargaRenuentes();
            datosCargaRenuentes.setGoodRegistros(goodReg);
            datosCargaRenuentes.setNombreArchivo(shortFileName);
            datosCargaRenuentes.setTotRegistros(totalReg);
            datosCargaRenuentes.setWrongRegistros(badReg);
            listaDatosCarga = new ArrayList<DatosCargaRenuentes>();
            listaDatosCarga.add(datosCargaRenuentes);

            getLogger().info("***** Nombre completo del archivo: " + nombreArchivo + " *****");
            getLogger().info("***** Nombre del archivo: " + shortFileName + " *****");

            //Generar archivo de errores
            this.generaArchivoErrores(listaErrores);

        } catch (IOException e) {
            getLogger().error(e.getMessage());
        } finally {
            if (br != null) {
                try {
                    br.close();
                } catch (IOException e) {
                    getLogger().error(e.getMessage());
                }
            }
        }
    }

    /**
     * Metodo para generar el archivo de bitacora
     *
     * @param listaErrores
     */
    private void generaArchivoErrores(List<String> listaErrores) {
        if (listaErrores.size() > 0) {
            try {
                this.showButtonBitacora = true;
                StringBuilder infoBuilder = new StringBuilder();
                for (String info : listaErrores) {
                    infoBuilder.append(info).append("\n");
                }
                this.saveFile(infoBuilder.toString(), bitacoraFileName);
            } catch (IOException ex) {
                getLogger().error(ex.getMessage());
            }
        } else {
            this.showButtonBitacora = false;
        }
        try {
            guardarBitacora(ConstantsCatalogos.CARGA_MOV_RENUENTES, ConstantsCatalogos.CARGA_RENUENTES_OBS);
        } catch (Exception e) {
            getLogger().error(e.getMessage());
        }
    }

    /**
     * @param numControl
     */
    private boolean updateRenuente(String numControl) {
        boolean resp = false;
        try {
            resp = doctoRenuenteService.updateConsideraRenuenciaDocto(numControl);
            try {
                guardarBitacora(ConstantsCatalogos.ACTUALIZA_ESTADO_RENUENTES, ConstantsCatalogos.CARGA_RENUENTES_OBS);
            } catch (Exception e) {
                getLogger().error(e.getMessage());
            }

ControlObligaciones/ControlObligacionesWeb/src/main/webapp/pages/cob/cargaRenuentes.xhtml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<f:view xmlns:f="http://java.sun.com/jsf/core"
        xmlns:h="http://java.sun.com/jsf/html"
        xmlns:p="http://primefaces.org/ui"
        xmlns:ui="http://java.sun.com/jsf/facelets">
    <html xmlns="http://www.w3.org/1999/xhtml">
        <h:head>
            <title>Carga Renuentes</title>
        </h:head>
        <ui:include src="/WEB-INF/templates/version.xhtml"/>
        <h:outputStylesheet library="css/" name="estilos.css"/>
        <script type="text/javascript">
            function msgErrorConcurrencia() {
                $('#msgErrorRenuenteVal').html('No se puede cargar el archivo, se esta procesando uno anterior');
                msgErrorRenuente.show();
            }
            function tiempoEspera() {
                setTimeout("enviaMensaje()", 200000);
            }
            function enviaMensaje() {
                msgSesionCaducada.show();
            }
        </script>
        <h:body>
            <ui:include src="/WEB-INF/templates/sessionTimeOut.xhtml"/> 
            <p:dialog modal="true" widgetVar="msgSesionCaducada" 
                      header="El proceso de carga de resultados se está ejecutando."
                      draggable="false" 
                      closable="false" resizable="false">
                <h:panelGrid columns="1" style="text-align: center;">
                    <p:outputLabel value="Al finalizar exitosamente recibirá un correo electrónico de notificación"/>

                    <p:commandButton value="Cerrar" action="#{cargaRenuentes.reloadPage}"/>
                </h:panelGrid>
            </p:dialog>
            <p:dialog modal="true" widgetVar="statusDialog" 
                      header="#{mensajes['msgEspere']}" draggable="false" 
                      closable="false" resizable="false">
                <p:graphicImage value="/resources/images/ajaxloadingbar.gif"/>
            </p:dialog>


            <h:form id="formaArchivo">
                <p:panel style="width:700px;margin-left:auto;margin-right:auto;border:none">
                    <p:messages id="messages" globalOnly="true" closable="true"/>
                </p:panel>
                <p:panel id="panelArchivo" header="Carga archivo previo" 
                         style="width:650px;margin-left:auto;margin-right:auto;" 
                         visible="#{cargaRenuentes.mostrarPanelArchivo}">
                    <h:panelGrid id="gridArchivo" columns="3" cellspacing="3" cellpadding="3">

                        <h:outputText  value="#{mensajes['etNombreArchivo']}"/>
                        <p:outputLabel value="#{cargaRenuentes.archivoRenuente.nombreArchivoCarga}" />
                        <h:outputText />
                        <h:outputText  value="#{mensajes['etFechaCarga']}"/>
                        <p:outputLabel value="#{cargaRenuentes.archivoRenuente.fechaCargaStr}" />
                        <h:outputText />
                        <h:outputText  value="#{mensajes['renuentes.numRegistros']}"/>
                        <p:outputLabel value="#{cargaRenuentes.archivoRenuente.totalRegistrosArchivoCarga}" />
                        <h:outputText />
                        <h:outputText  value="#{mensajes['renuentes.registrosErrores']}"/>
                        <p:outputLabel value="#{cargaRenuentes.archivoRenuente.totalRegistrosErrores}" />
                        <h:outputText />
                        <h:outputText  value="#{mensajes['etBitacoraCarga']}" 
                                       rendered="#{cargaRenuentes.mostrarMensajeArchivo||cargaRenuentes.mostrarBotonDescargaArchivo}"/>
                        <p:commandButton ajax="false" value="Descargar" rendered="#{cargaRenuentes.mostrarBotonDescargaArchivo}">
                            <p:fileDownload value="#{cargaRenuentes.bitacoraFile}" id="downloaderArchivo"/>
                        </p:commandButton>
                        <p:outputLabel value="#{cargaRenuentes.muestraMensaje}" rendered="#{cargaRenuentes.mostrarMensajeArchivo}"/>

                    </h:panelGrid>
                </p:panel>
            </h:form>

            <br/>

            <h:form id="formaUploader" enctype="multipart/form-data">
                <p:panel id="pnluploader" header="Seleccion de archivo" style="width:650px;margin-left:auto;margin-right:auto;">
                    <p:fileUpload fileUploadListener="#{cargaRenuentes.handleFileUpload}" mode="advanced"
                                  auto="true"
                                  dragDropSupport="false" 
                                  sizeLimit="1000000000" multiple="false"
                                  update=":formaArchivo:panelArchivo, :formaArchivo:messages" 
                                  onstart="tiempoEspera(); statusDialog.show();remoteCommandUpdateDataTable();"
                                  oncomplete="statusDialog.hide();"
                                  allowTypes="/(\.|\/)(txt|TXT)$/"
                                  invalidFileMessage="#{mensajes['ui.componente.fileupload.invalidLabel']}"
                                  label="#{mensajes['ui.componente.fileupload.examineLabel']}"
                                  uploadLabel="#{mensajes['ui.componente.fileupload.uploadLabel']}"
                                  cancelLabel="#{mensajes['ui.componente.fileupload.cancelLabel']}" />
                    <p:remoteCommand name="remoteCommandUpdateDataTable" update=":formaUploader:pnluploader"/>
                </p:panel>

                <p:dialog header="Mensaje" widgetVar="msgErrorRenuente" modal="true"
                          resizable="false" draggable="false" >
                    <p><div id="msgErrorRenuenteVal"></div></p>
                    <p:commandButton value="Aceptar" onclick="msgErrorRenuente.hide();"/>
                </p:dialog>
            </h:form>
        </h:body>
    </html>
</f:view>

ControlObligaciones/ControlObligacionesWeb/src/main/webapp/pages/cob/cargaRenuentesBis.xhtml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<f:view xmlns:f="http://java.sun.com/jsf/core" xmlns:h="http://java.sun.com/jsf/html" xmlns:p="http://primefaces.org/ui"
        >
    <html xmlns="http://www.w3.org/1999/xhtml"
          xmlns:ui="http://java.sun.com/jsf/facelets">
        <h:head>
            <title>cargaRenuentesBis</title>
        </h:head>
        <ui:include src="/WEB-INF/templates/version.xhtml"/>
        <h:outputStylesheet library="css/" name="estilos.css"/>
        <h:body>
            <script type="text/javascript">
                function showStatus() {
                    statusDialog.show();
                }
                function hideStatus() {
                    statusDialog.hide();
                }
            </script>            
            <h:outputStylesheet library="css/" name="estilos.css"/>
            <ui:include src="/WEB-INF/templates/sessionTimeOut.xhtml"/>

            <p:dialog modal="true" widgetVar="statusDialog" header="Procesando" draggable="false" closable="false" resizable="false">
                <table width="100%">
                    <tr align="center">
                        <td align="center">
                            <p:outputLabel value="Cargando informacion. Espere por favor." />
                        </td>
                    </tr>
                    <tr><td></td></tr>
                    <tr align="center">
                        <td align="center">
                            <p:graphicImage value="/resources/images/ajaxloading.gif" />  
                        </td>
                    </tr>
                </table>            
            </p:dialog>

            <h:form id="formaUploader" prependId="false" enctype="multipart/form-data">
                <p:panel header="Seleccion de archivo" style="width:650px;margin-left:auto;margin-right:auto;">
                    <p:fileUpload value="#{cargaRenuentesBis.file}" mode="simple"
                                  dragDropSupport="false" update="panelArchivosRenuentes" sizeLimit="100000" multiple="false"
                                  allowTypes="/(\.|\/)(txt)$/"/>
                    <br/>
                    <br/>
                    <p:commandButton value="Validar" ajax="false" actionListener="#{cargaRenuentesBis.procesarArchivo}" onclick="PrimeFaces.monitorDownload(showStatus, hideStatus)"/>&nbsp;
                    <h:outputText value="Nota: Al validar el archivo, se cambiar&aacute; el estado de los documentos a renuentes." style="color: red"/>

                </p:panel>

                <p:panel id="panelArchivosRenuentes" header="#{mensajes['ui.cifrascontrol.panel.header']}"
                         visible="true" style="width:650px;margin-left:auto;margin-right:auto;">
                    <p:dataTable var="detalle" value="#{cargaRenuentesBis.listaDatosCarga}"
                                 emptyMessage="No hay archivos cargados aún" id="cifrasControl">
                        <p:column style="text-align:center;height:30px;">
                            <f:facet name="header">
                                <h:outputText value="#{mensajes['ui.componente.omisos.col1']}"/>
                            </f:facet>
                            <h:outputText value="#{detalle.nombreArchivo}"/>
                        </p:column>
                        <p:column style="text-align:center;">
                            <f:facet name="header">
                                <h:outputText value="#{mensajes['ui.componente.omisos.col2']}"/>
                            </f:facet>
                            <h:outputText value="#{detalle.totRegistros}"/>
                        </p:column>
                        <p:column style="text-align:center;">
                            <f:facet name="header">
                                <h:outputText escape="false" value="#{mensajes['ui.componente.omisos.col3']}"/>
                            </f:facet>
                            <h:outputText value="#{detalle.goodRegistros}"/>
                        </p:column>
                        <p:column style="text-align:center;">
                            <f:facet name="header">
                                <h:outputText escape="false"
                                              value="#{mensajes['ui.componente.bitacora.detalle.col3']}"/>
                            </f:facet>
                            <h:outputText value="#{detalle.wrongRegistros}"/>
                        </p:column>
                        <p:column style="text-align:center;">
                            <f:facet name="header">
                                <h:outputText value="#{mensajes['ui.componente.bitacora.detalle.col4']}"/>
                            </f:facet>
                            <p:commandButton rendered="#{cargaRenuentesBis.showButtonBitacora}" ajax="false"
                                             icon="ui-icon-circle-arrow-s">
                                <p:fileDownload value="#{cargaRenuentesBis.bitacoraFile}" id="downloader"/>
                            </p:commandButton>
                        </p:column>
                    </p:dataTable>
                </p:panel>


            </h:form>
        </h:body>
    </html>
</f:view>