ControlObligaciones/ControlObligacionesWeb/src/main/java/mx/gob/sat/siat/cob/seguimiento/web/controller/bean/backing/AdministracionFuncionariosManagedBean.java
package mx.gob.sat.siat.cob.seguimiento.web.controller.bean.backing;

import java.util.List;
import javax.annotation.PostConstruct;
import mx.gob.sat.siat.cob.seguimiento.dto.catalogos.ComboStr;
import mx.gob.sat.siat.cob.seguimiento.dto.compartidos.CatalogoBase;
import mx.gob.sat.siat.cob.seguimiento.dto.stdcob.FuncionarioSat;
import mx.gob.sat.siat.cob.seguimiento.exception.SGTServiceException;
import mx.gob.sat.siat.cob.seguimiento.service.otros.AdministracionFuncionariosService;
import mx.gob.sat.siat.cob.seguimiento.util.constante.ConstantsCatalogos;
import mx.gob.sat.siat.cob.seguimiento.utils.AbstractBaseMB;
import mx.gob.sat.siat.controlador.AccesoProceso;
import mx.gob.sat.siat.exception.AccesoDenegadoException;
import mx.gob.sat.siat.exception.AccesoDenegadoFielException;
import mx.gob.sat.siat.exception.SessionRolNullException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

@Controller("admonFuncionarios")
@Scope(value = "view")
public class AdministracionFuncionariosManagedBean extends AbstractBaseMB {

    @Autowired
    private AdministracionFuncionariosService administracionFuncionariosService;
    private List<FuncionarioSat> funcionarios;
    private List<FuncionarioSat> funcionariosTemp;
    private List<CatalogoBase> cargosAdministrativos;
    private List<CatalogoBase> nivelesEmision;
    private List<CatalogoBase> eventoCarga;
    private List<ComboStr> regionALR;
    private List<ComboStr> empleadosAdmtvo;
    private FuncionarioSat empleado;
    private FuncionarioSat empleadoEditar = new FuncionarioSat();
    private FuncionarioSat empleadoDTO = new FuncionarioSat();
    private FuncionarioSat empleadoAux = new FuncionarioSat();
    private boolean mostrarPanelEliminar;
    private boolean mostrarPanelTabla;
    private boolean mostrarPanelGuardar;
    private boolean mostrarPanelEditar;
    private boolean mostrarComboRegion;
    private boolean mostrarBotonGuardar;
    private boolean mostrarPanelContinuar;
    private boolean mostrarPanelHabilitarContinuar;

    public AdministracionFuncionariosManagedBean() {
        super();
    }

    @PostConstruct
    public void init() {

        try {
            obtenerAccesoUsrEmpleados();
            if (AccesoProceso.validaAccesoProceso(getSession(), "COB00028", ConstantsCatalogos.PARAMETRO_FIEL)) {
                empleadosAdmtvo = administracionFuncionariosService.obtenerEmpleadosAdministrativo();
                funcionarios = administracionFuncionariosService.buscarFuncionarios();
                nivelesEmision = administracionFuncionariosService.buscarNivelesEmision();
                regionALR = administracionFuncionariosService.buscarRegionALR();
                cerrar();
                setMostrarBotonGuardar(true);
                setMostrarPanelContinuar(false);
            }
        } catch (SGTServiceException e) {
            getLogger().error(e.getMessage());

        } catch (SessionRolNullException ex) {
            getLogger().error("Error de Sesion:" + ex.getMessage());
            manejaException(ex);
        } catch (AccesoDenegadoException ex) {
            getLogger().error("Error de acceso denegado:" + ex.getMessage());
            manejaException(ex);
        } catch (AccesoDenegadoFielException ex) {
            getLogger().error("Error de acceso denegado fiel:" + ex.getMessage());
            manejaException(ex);
        }
    }

    private void manejaException(Exception e) {
        getSession().setAttribute("mensaje", e.getMessage());
        redirigir(ConstantsCatalogos.URL_EN_CONSTRUCCION);
    }

    public void habilitarComboRegion() {
        setMostrarComboRegion((empleadoDTO.getNivelEmision() == 1));
        cargosAdministrativos =
                administracionFuncionariosService.buscarCargoPorNivelEmision(empleadoDTO.getNivelEmision());
        eventoCarga = administracionFuncionariosService.buscarEventoCarga(empleadoDTO.getNivelEmision());

    }

    public void habilitarComboRegionUpdate() {
        setMostrarComboRegion((empleadoEditar.getNivelEmision() == 1));
        cargosAdministrativos =
                administracionFuncionariosService.buscarCargoPorNivelEmision(empleadoEditar.getNivelEmision());
        eventoCarga = administracionFuncionariosService.buscarEventoCarga(empleadoEditar.getNivelEmision());
        if (empleadoEditar.getNivelEmision() != 1) {
            empleadoEditar.setIdRegionAlr(null);
        }
    }

    public void mostrarPaneles() {
        setMostrarBotonGuardar(false);
        if (mostrarPanelGuardar) {
            setMostrarPanelContinuar(true);
        }
        if (mostrarPanelEditar) {
            setMostrarPanelContinuar(false);
            setMostrarPanelHabilitarContinuar(true);
        }
        if (empleadoEditar.getFechaFin() != null) {
            setMostrarPanelContinuar(false);
            setMostrarPanelHabilitarContinuar(true);
       }
    }

    public boolean isEditar() {
        if ((mostrarPanelEditar && empleadoEditar != null && empleadoEditar.getIdEventoCarga() == 1)) {
            return true;
        }
        return false;
    }

    public boolean isGuardar() {
        if ((mostrarPanelGuardar && empleadoDTO != null && empleadoDTO.getIdEventoCarga() == 1)) {
            return true;
        }
        return false;
    }

    public void addWarn() {
        if (isEditar() || isGuardar()) {
            if (administracionFuncionariosService.validarFuncionarioExistente(mostrarPanelEditar ? empleadoEditar
                    : empleadoDTO, this.getFuncionarios())) {
                addWarningMessage("Ya existe un funcionario con estos datos Al presionar el boton Continuar, ser\u00e1 reemplazado", "");
                mostrarPaneles();

            } else {
                mostrarPaneles();
                guardar();
            }
        } else {
            mostrarPaneles();
            guardar();
        }
    }

    public void cancelar() {
        setMostrarBotonGuardar(true);
        setMostrarPanelContinuar(false);
        setMostrarPanelHabilitarContinuar(false);
        cerrar();
    }

    public void guardar() {
        if (mostrarPanelGuardar) {
            guardarEmpleado();
        }
        if (mostrarPanelEditar) {
            actualizarRegistroEmpleado();
        }
        if (empleadoEditar.getFechaFin() != null) {
            habilitarRegistroEmpleado();
        }
    }

    public void guardarEmpleado() {
        try {
            if(!administracionFuncionariosService.buscarEmpleadosNumEvento(empleadoDTO, funcionarios)){
            administracionFuncionariosService.guardarFuncionario(empleadoDTO);
            funcionarios = administracionFuncionariosService.buscarFuncionarios();
            super.addMessage("Se guardo exitosamente el empleado", "");
            }else{
                super.addErrorMessage("Ya existe un registro en base de datos con el mismo n\u00famero de empleado y el mismo evento de carga", "");
                getLogger().error("Ya existe un registro en base de datos con el mismo n\u00famero de empleado y el mismo evento de carga");
            }
            cerrar();
        } catch (SGTServiceException e) {
            setMostrarBotonGuardar(true);
            setMostrarPanelContinuar(false);
            super.addErrorMessage(e.getMessage(), "");
        }
    }

    public void actualizarRegistroEmpleado() {
        try {
            if (empleadoEditar.getFechaFin() == null) {
                administracionFuncionariosService.actualizarRegistroFuncionario(empleadoEditar);
                funcionarios = administracionFuncionariosService.buscarFuncionarios();
                funcionariosTemp = administracionFuncionariosService.buscarFuncionarios();
                cerrar();
                super.addMessage("Se guardo exitosamente el empleado", "");
            }
        } catch (SGTServiceException e) {
            cerrar();
            super.addErrorMessage(e.getMessage(), "");
            getLogger().error(e.getMessage());
        }
    }

    public void habilitarRegistroEmpleado() {
        try {
            administracionFuncionariosService.habilitarRegistroFuncionario(empleadoEditar);
            funcionarios = administracionFuncionariosService.buscarFuncionarios();
            funcionariosTemp = administracionFuncionariosService.buscarFuncionarios();
            cerrar();
        } catch (SGTServiceException e) {
            cerrar();
            super.addErrorMessage(e.getMessage(), "");
            getLogger().error(e.getMessage());
        }
    }

    public void eliminarRegistroEmpleado() {

        administracionFuncionariosService.eliminarRegistroFuncionario(empleado.getNumeroEmpleado(), empleado.getIdEventoCarga());
        funcionarios = administracionFuncionariosService.buscarFuncionarios();
        funcionariosTemp = administracionFuncionariosService.buscarFuncionarios();
        cerrar();

    }

    public void abrirGuardar() {

        setMostrarPanelGuardar(true);
        setMostrarBotonGuardar(true);
        setMostrarPanelEliminar(false);
        setMostrarPanelTabla(false);
        setMostrarPanelEditar(false);

    }

    public void abrirEditar() {
        setMostrarComboRegion((empleadoEditar.getNivelEmision() == 1));
        cargosAdministrativos =
                administracionFuncionariosService.buscarCargoPorNivelEmision(empleadoEditar.getNivelEmision());
        eventoCarga = administracionFuncionariosService.buscarEventoCarga(empleadoEditar.getNivelEmision());
        getLogger().error("valor:" + mostrarComboRegion);
        setMostrarPanelEliminar(false);
        setMostrarPanelTabla(false);
        setMostrarPanelGuardar(false);
        setMostrarPanelEditar(true);
    }

    public void abrirEliminar() {
        setMostrarPanelEliminar(true);
        setMostrarPanelTabla(false);
        setMostrarPanelGuardar(false);

ControlObligaciones/ControlObligacionesWeb/src/main/java/mx/gob/sat/siat/cob/seguimiento/web/controller/bean/backing/AprobarMultaGruposManagedBean.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.gob.sat.siat.cob.seguimiento.web.controller.bean.backing;


import javax.annotation.PostConstruct;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpSession;
import mx.gob.sat.siat.cob.seguimiento.dto.stdcob.AdministrativoNivelCargo;
import mx.gob.sat.siat.cob.seguimiento.dto.stdcob.MultaAprobarGrupo;
import mx.gob.sat.siat.cob.seguimiento.dto.stdcob.enums.EventoCargaEnum;
import mx.gob.sat.siat.cob.seguimiento.exception.SGTServiceException;
import mx.gob.sat.siat.cob.seguimiento.service.aprobacion.AprobarMultasService;
import mx.gob.sat.siat.cob.seguimiento.service.aprobacion.impl.AprobarMultasCountThread;
import mx.gob.sat.siat.cob.seguimiento.service.otros.AdministracionFuncionariosService;
import mx.gob.sat.siat.cob.seguimiento.util.IntegerMutable;
import mx.gob.sat.siat.cob.seguimiento.util.constante.ConstantsCatalogos;
import mx.gob.sat.siat.cob.seguimiento.utils.AbstractBaseMB;
import mx.gob.sat.siat.cob.seguimiento.web.controller.bean.backing.helper.AprobarMultaGruposManagedBeanHelper;
import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

/**
 *
 * @author root
 */
@Controller("aprobarMultaGruposMB")
@Scope(value = "view")
public class AprobarMultaGruposManagedBean extends AbstractBaseMB  {
    @Autowired
    private AprobarMultasService aprobarMultasService;
    @Autowired
    private AdministracionFuncionariosService administracionFuncionariosService;
    @Autowired
    private ApplicationContext applicationContext;
    private AprobarMultaGruposManagedBeanHelper aprobarMultaGruposManagedBeanHelper;
    private boolean botonDescargaVisible = false;
    private Integer progress = 0;
    private AprobarMultasCountThread thread;
    private AdministrativoNivelCargo administrativo;

    public AprobarMultaGruposManagedBean() {
        aprobarMultaGruposManagedBeanHelper = new AprobarMultaGruposManagedBeanHelper();
        aprobarMultaGruposManagedBeanHelper.setNombreArchivoDescarga((String) ((HttpSession) FacesContext.
                getCurrentInstance().
                getExternalContext().
                getSession(true)).
                getAttribute("archivoResultadosEmisionMulta"));
        ((HttpSession) FacesContext.
                getCurrentInstance().
                getExternalContext().
                getSession(true)).removeAttribute("archivoResultadosEmisionMulta");
        if(aprobarMultaGruposManagedBeanHelper.getNombreArchivoDescarga()!=null){
            botonDescargaVisible = true;
        }
    }
    @PostConstruct
    public void init() {
        try {
            obtenerAccesoUsrEmpleados();
            autorizar(ConstantsCatalogos.IDENTIFICADOR_EMISION_MULTAS);
            administrativo = administracionFuncionariosService.buscarCargoAdministrativo(this.getAccesoUsr().getNumeroEmp(), EventoCargaEnum.CARGA_OMISOS);
            aprobarMultaGruposManagedBeanHelper.setListaMultasGrupo(aprobarMultasService.listarMultasAgrupadas(administrativo));
            aprobarMultaGruposManagedBeanHelper.setProgress(new IntegerMutable());
            aprobarMultaGruposManagedBeanHelper.getProgress().setValor(0);
        } catch (SGTServiceException ex) {
            this.getLogger().error(ex);
            addErrorMessage("Error", ex.getMessage());
        }
    }

    public AprobarMultaGruposManagedBeanHelper getAprobarMultaGruposManagedBeanHelper() {
        return aprobarMultaGruposManagedBeanHelper;
    }

    public void setAprobarMultaGruposManagedBeanHelper(AprobarMultaGruposManagedBeanHelper aprobarMultaGruposManagedBeanHelper) {
        this.aprobarMultaGruposManagedBeanHelper = aprobarMultaGruposManagedBeanHelper;
    }
    
    //Se agrega processo thread
    public void setMultaAprobarGrupo(MultaAprobarGrupo multaAprobarGrupo) {
        try {            
            thread = applicationContext.getBean(AprobarMultasCountThread.class);
            thread.establecerValoresEjecucion(multaAprobarGrupo,
                                            administrativo,
                                            aprobarMultaGruposManagedBeanHelper.getProgress());
            thread.start();
            
            getSession().setAttribute("multaAprobarGrupo", multaAprobarGrupo);
            
        }catch(Exception e){
            getLogger().error(e.getMessage());
        }
    }

    public boolean isBotonDescargaVisible() {
        return botonDescargaVisible;
    }
    
    public StreamedContent getDescargaEmision() {
        StreamedContent sc = null;
        try {
            sc = new DefaultStreamedContent(aprobarMultasService.generarArchivoEmision(aprobarMultaGruposManagedBeanHelper.getNombreArchivoDescarga()),
                                                 "application/pdf", aprobarMultaGruposManagedBeanHelper.getNombreArchivoDescarga());
        } catch (SGTServiceException e) {
            this.getLogger().error(e);
            addErrorMessage("Error", e.getMessage());
            aprobarMultaGruposManagedBeanHelper.setMultaAprobarDescarga(null);
            botonDescargaVisible=false;
        }
        return sc;
    }
    public void mensajeEmision(){
        if(aprobarMultaGruposManagedBeanHelper.getMultaAprobarDescarga()!=null){
            if(aprobarMultaGruposManagedBeanHelper.getMultaAprobarDescarga().getCantidadPosiblesEmitir().
                    equals(aprobarMultaGruposManagedBeanHelper.getMultaAprobarDescarga().getCantidadMultasEmitidas())){
                addMessage(null, "Los multas fueron emitidas exitosamente. Verifique el archivo de descarga");
            }else{
                addErrorMessage("Error", "No todas las multas pudieron ser emitidas. Verifique el archivo de descarga");
            }
            botonDescargaVisible = true;
        }
        
    }

    public Integer getProgress() {
        return progress;
    }

    public void setProgress(Integer progress) {
        this.progress = progress;
    }
    
    public void increment() {
        progress++;
        this.getLogger().debug("\nel número de llamadas del poll va en " + progress);
    }
    
    public void irMultasIndividuales() {
        MultaAprobarGrupo multaAprobarGrupo = (MultaAprobarGrupo) getSession().getAttribute("multaAprobarGrupo");

        if (thread.getNumeroElementos() != null) {
            multaAprobarGrupo.setConteoElementos(thread.getNumeroElementos());
        }

        if (thread.getException() != null) {
            getLogger().error(thread.getException().getMessage());
        }

        getSession().setAttribute("multaAprobarGrupo", multaAprobarGrupo);
        
        redirigir("/pages/cob/aprobarVigilancias/aprobarMulta.jsf");

    }
}

ControlObligaciones/ControlObligacionesWeb/src/main/webapp/pages/cob/aprobarVigilancias/aprobarMultaGrupo.xhtml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<f:view xmlns:f="http://java.sun.com/jsf/core" 
        xmlns:h="http://java.sun.com/jsf/html"
        xmlns:p="http://primefaces.org/ui"
        xmlns:ui="http://java.sun.com/jsf/facelets">
    <html xmlns="http://www.w3.org/1999/xhtml">
        <h:head>
            <title>Aprobar Multas</title>
        </h:head>
        <ui:include src="/WEB-INF/templates/version.xhtml"/>
        <h:outputScript library="js" name="visualizaDocsFirmaJs.js"/>
        <ui:include src="/WEB-INF/templates/loader.xhtml"/>
        <f:event listener="#{aprobarMultaGruposMB.mensajeEmision}" type="preRenderView" />
        <h:body>            
            <h:outputStylesheet library="css/" name="estilos.css"/>
            <ui:include src="/WEB-INF/templates/loader.xhtml"/>
            <h:form id="mostrarMultasGrupo" prependId="false">
                <p:messages id="mensajes" showDetail="true" showSummary="true"/>
                <p:panel styleClass="panel-princial" style="width:800px;margin-left:auto;margin-right:auto;" visible="true">                   
                    <p:dataTable value="#{aprobarMultaGruposMB.aprobarMultaGruposManagedBeanHelper.listaMultasGrupo}"
                                 var="multaGrupo"
                                 paginator="true"
                                 paginatorPosition="bottom"
                                 rows="12"
                                 paginatorAlwaysVisible="false"
                                 id="tblVigilancias"
                                 emptyMessage="#{mensajes['msg.dataTable.vacio']}">                        
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{mensajes['aprobarVigilanciaRenuentes.fechaEmision']}"/>
                            </f:facet>
                            <p:commandLink value="#{multaGrupo.fechaEmision}" style="color: blue" onclick="pbAjax.start();
                                             dlgBarraEstado.show();">
                                <f:setPropertyActionListener value="#{multaGrupo}"
                                                             target="#{aprobarMultaGruposMB.multaAprobarGrupo}"/>
                            </p:commandLink>
                        </p:column>                            
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{mensajes['aprobarVigilanciaRenuentes.medioEnvio']}"/>
                            </f:facet>
                            <h:outputText value="#{multaGrupo.medioEnvio}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{mensajes['aprobarVigilanciaRenuentes.tipoFirma']}"/>
                            </f:facet>
                            <h:outputText value="#{multaGrupo.tipoFirma}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{mensajes['aprobarMultas.tipoMulta']}"/>
                            </f:facet>
                            <h:outputText value="#{multaGrupo.tipoMulta}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{mensajes['aprobarMultas.numeroMultas']}"/>
                            </f:facet>
                            <h:outputText value="#{multaGrupo.cantidadMultas}"/>
                        </p:column>
                    </p:dataTable>
                    <p:dialog header="Procesando..." 
                              widgetVar="dlgBarraEstado"
                              draggable="false"
                              closable="false"
                              resizable="false"
                              modal="true"
                              onShow="poll.start();"
                              onHide="poll.stop();"
                              id="dialogoBarra">
                        <h:outputText value="Consultando, por favor espere..."/>
                        <p:progressBar widgetVar="pbAjax" 
                                       ajax="true" 
                                       value="#{aprobarMultaGruposMB.aprobarMultaGruposManagedBeanHelper.progress.valor}" 
                                       labelTemplate="{value}%" 
                                       styleClass="animated"
                                       interval="1000">  
                            <p:ajax event="complete" 
                                    oncomplete="dlgBarraEstado.hide();pbAjax.setValue(0);dlg2.show();redirigir();" update="@form"/>  
                        </p:progressBar>  
                    </p:dialog>
                </p:panel>
                <p:commandButton value="descarga" styleClass="botonDescargaInicio"  ajax="false"
                                 rendered="#{aprobarMultaGruposMB.botonDescargaVisible}">
                    <p:fileDownload value="#{aprobarMultaGruposMB.descargaEmision}"/>
                </p:commandButton>
                <p:dialog header="Redirigiendo..." widgetVar="dlg2" modal="true" draggable="false" closable="false">
                    <h:outputText value="Redirigiendo pagina solicitada..." />
                </p:dialog>   
                <p:remoteCommand name="redirigir" actionListener="#{aprobarMultaGruposMB.irMultasIndividuales}"/>
                <p:poll interval="10" listener="#{aprobarMultaGruposMB.increment}"
                        widgetVar="poll" autoStart="false"/>
            </h:form>            
        </h:body>
    </html>
</f:view>

ControlObligaciones/ControlObligacionesWeb/src/main/webapp/pages/cob/aprobarVigilancias/aprobarVigilanciaRenuentes.xhtml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<f:view xmlns:f="http://java.sun.com/jsf/core" 
        xmlns:h="http://java.sun.com/jsf/html"
        xmlns:p="http://primefaces.org/ui"
        xmlns:ui="http://java.sun.com/jsf/facelets">
    <html xmlns="http://www.w3.org/1999/xhtml">
        <h:head>
            <title>Aprobar Vigilancias Renuentes</title>
        </h:head>
        <ui:include src="/WEB-INF/templates/version.xhtml"/>
        <h:outputScript library="js/jquery" name="jquery-1.11.0.min.js"/>
        <h:outputScript library="js" name="visualizaDocsFirmaJs.js"/>
        <f:event listener="#{aprobarVigilanciaRenuentesMB.mensajeEmision}" type="preRenderView" />
        <h:body>            
            <h:outputStylesheet library="css/" name="estilos.css"/>
            <ui:include src="/WEB-INF/templates/loader.xhtml"/>
            <ui:include src="/WEB-INF/templates/sessionTimeOut.xhtml"/>
            <h:form id="mostrarVigilanciasForm" prependId="false">
                <p:messages id="mensajes" showDetail="true" showSummary="true"/>
                <p:panel styleClass="panel-princial">                   
                    <p:dataTable value="#{aprobarVigilanciaRenuentesMB.aprobarVigilanciaRenuentesHelper.vigilancias}"
                                 var="vigilancia"
                                 paginator="true"
                                 paginatorPosition="bottom"
                                 rows="12"
                                 paginatorAlwaysVisible="false"
                                 id="tblVigilancias"
                                 emptyMessage="#{mensajes['msg.dataTable.vacio']}">
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{mensajes['aprobarVigilanciaRenuentes.fechaEmision']}"/>
                            </f:facet>
                            <h:commandLink value="#{vigilancia.fechaEmision}" 
                                           action="#{aprobarVigilanciaRenuentesMB.irDocumentosRenuentes}">
                                <f:setPropertyActionListener value="#{vigilancia}"
                                                             target="#{aprobarVigilanciaRenuentesMB.vigilanciaGrupo}"/>
                            </h:commandLink>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{mensajes['aprobarVigilanciaRenuentes.medioEnvio']}"/>
                            </f:facet>
                            <h:outputText value="#{vigilancia.medioEnvio}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{mensajes['aprobarVigilanciaRenuentes.tipoFirma']}"/>
                            </f:facet>
                            <h:outputText value="#{vigilancia.tipoFirma}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{mensajes['aprobarVigilanciaRenuentes.tipoDocumento']}"/>
                            </f:facet>
                            <h:outputText value="#{vigilancia.tipoDocumento}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{mensajes['aprobarVigilanciaRenuentes.cantidadDocumentos']}"/>
                            </f:facet>
                            <h:outputText value="#{vigilancia.cantidadDocumentos}"/>
                        </p:column>
                    </p:dataTable>
                </p:panel>
                <p:commandButton value="descarga" styleClass="botonDescargaInicio" ajax="false"
                                 rendered="#{aprobarVigilanciaRenuentesMB.botonDescargaVisible}">
                    <p:fileDownload value="#{aprobarVigilanciaRenuentesMB.descargaEmision}"/>
                </p:commandButton> 
            </h:form>
        </h:body>
    </html>
</f:view>

ControlObligaciones/ControlObligacionesWeb/src/main/webapp/pages/cob/aprobarVigilancias/downloadFacturaMultimedia.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
    <h:head></h:head>
    <h:body>
        <h:head>
            <title>Download Factura Multimedia</title>
        </h:head>
        <ui:include src="/WEB-INF/templates/version.xhtml"/>

        <h:body>
            <h:outputStylesheet library="css/" name="estilos.css"/>
            <ui:include src="/WEB-INF/templates/sessionTimeOut.xhtml"/>
            <f:metadata>
                <f:event type="preRenderView" listener="#{facturaVigilancias.cargarArchivo}"/>
            </f:metadata>
            <h:form id="formaGeneralfactura" prependId="false">
                <p:panel styleClass="panel-principal">
                    <p:media value="#{facturaVigilancias.streamedContent}" player="pdf" width="100%" height="400px">  
                        Your browser can't display pdf 
                    </p:media>
                </p:panel>
                <p:panel styleClass="panel-principal" style="text-align: center">
                    <p:commandButton value="Descargar" 
                                     ajax="false">
                        <p:fileDownload value="#{facturaVigilancias.factura}"/>
                    </p:commandButton>
                    <p:commandButton id="idRegresarBtn" value="Regresar" action="#{facturaVigilancias.regresar}"></p:commandButton>
                    
                </p:panel>    
            </h:form>
        </h:body>
    </h:body>
</html>